### ISSUE TITLE
Connecting to Roblox Studio plugin gets stuck at reconnecting

### ISSUE THREAD

**Issue by Aerodymier** [NightrainsRbx/RobloxLsp#101]
This happens after closing a Studio place when plugin is connected. After that, other opened places will get stuck at "Reconnecting". I also re-opened VS Code but that didn't fix it.

**Comment by NightrainsRbx** [comment]
You should not expect the plugin to output when it's connected, if it says Reconnecting, probably it has already connected. In VSCode on the other hand, it shows a notification when it gets connected to the plugin, but it only shows it the first time, if you reconnect it will not show again.

Maybe it works but you are expecting something to happen after the "Reconnecting" message, if it doesn't work, you should make sure the ports used are the same.

**Comment by Aerodymier** [comment]
Reconnecting text repeats in output. It was on (x12) when I stopped the plugin and decided that it's a bug.

**Comment by NightrainsRbx** [comment]
> Reconnecting text repeats in output. It was on (x12) when I stopped the plugin and decided that it's a bug.

I found the problem, you have to exclude things in your game like Workspace in the Roblox Studio plugin settings, because the Roblox LSP extensions now has a limit of 1mb of receiving data, and you may be surpassing it.

**Comment by Aerodymier** [comment]
It would be good if it can print an informative text when this happens. If you think that this would be obsolete then this issue can be closed.

**Comment by NightrainsRbx** [comment]
> It would be good if it can print an informative text when this happens. If you think that this would be obsolete then this issue can be closed.

That's something I will implement soon

**Comment by Aerodymier** [comment]
> > Reconnecting text repeats in output. It was on (x12) when I stopped the plugin and decided that it's a bug.
> 
> I found the problem, you have to exclude things in your game like Workspace in the Roblox Studio plugin settings, because the Roblox LSP extensions now has a limit of 1mb of receiving data, and you may be surpassing it.

I forgot to ask this yesterday, can this somehow get configured by user?

**Comment by NightrainsRbx** [comment]
> > > Reconnecting text repeats in output. It was on (x12) when I stopped the plugin and decided that it's a bug.
> > 
> > 
> > I found the problem, you have to exclude things in your game like Workspace in the Roblox Studio plugin settings, because the Roblox LSP extensions now has a limit of 1mb of receiving data, and you may be surpassing it.
> 
> I forgot to ask this yesterday, can this somehow get configured by user?

No, you can't, but I will increase the limit since I thought 1mb was too much but many people are facing issues due to the limit being surpassed.

**Comment by NightrainsRbx** [comment]
The limit has been increased to 3mb and the Roblox Studio plugin has been updated to warn when this limit is surpassed.
