### ISSUE TITLE
Support genric function types

### ISSUE THREAD

**Issue by Testure** [NightrainsRbx/RobloxLsp#104]
Roblox recently release support for luau generic functions and I noticed there's no support for them in RobloxLsp.

Although it's possible to use generic functions in a way that functions fine in Studio, getting errors and not getting proper highlighting support in the editor is a bit of a problem.

**Comment by NightrainsRbx** [comment]
This commit f7998131594611ec378d18dcde4957233049439f adds syntax support, and definition.

I'm planning to add full support for generic functions but this will come after implementing generics in general.
