### ISSUE TITLE
stop the plugin from connecting during playlists

### ISSUE THREAD

**Issue by Baileyeatspizza** [NightrainsRbx/RobloxLsp#107]
the title basically explains it but the plugin will constantly try to reconnect during playtests which is a huge issue as the client can't make http requests so it loops forever just add a simple RunService:IsEdit() at the start of the plugins code

;(
https://gyazo.com/d3768d8db929125859d6eb64f5ea0838

**Comment by NightrainsRbx** [comment]
I cannot replicate this problem, the Roblox LSP plugin already checks if it's in Edit Mode.
![image](https://user-images.githubusercontent.com/69439321/137043417-0f12b2a1-a4ab-40e7-ae6d-0aee0de33eef.png)

So your problem has to do with something else, try to detail what happens and make a list of steps to reproduce it.

**Comment by NightrainsRbx** [comment]
I have seen this same problem, the instance tree is surpassing the limit of 1mb, you have to exclude instances like the Workspace to reduce its size.

I increased the limit to 3mb and updated the Roblox Studio plugin to warn when that limit is surpassed.
