### ISSUE TITLE
Indentation occurs after using the new "if" expression

### ISSUE THREAD

**Issue by MattSchrubb** [NightrainsRbx/RobloxLsp#113]
When using the new if expression, `local t = if true then 1 else 2`, an indentation occurs after returning to a new line and only goes back to normal after adding `end` like it's a normal `if end` block.

**Comment by NightrainsRbx** [comment]
I'm assuming you are using VSCode. 

You need to disable the built-in extension for Lua, that extension overrides the language configuration of Roblox LSP.

**Comment by MattSchrubb** [comment]
Thanks, got it working. Only took forever because I didn't know I needed to restart VSCode after disabling the Language Detection setting.

**Comment by matthargett** [comment]
Looks like this can be closed?

**Comment by MattSchrubb** [comment]
Yes, sorry I forgot about this
