### ISSUE TITLE
Extension fails to load because of missing module

### ISSUE THREAD

**Issue by Zamdie** [NightrainsRbx/RobloxLsp#115]
The Roblox LSP extension fails to load because of a missing module:

![image](https://user-images.githubusercontent.com/74075188/141857751-86c9ca70-d484-49fd-a32c-8ccebbd63cb0.png)
The error comes from the `client/out/languageserver.js` file at line 18, which requires the `vscode-languageclient/node` module.

OS: Arch Linux
Extension version: 1.5.1

**Comment by NightrainsRbx** [comment]
Run `npm install` inside the extension client folder.

This bug is because you are using VSCodium which doesn't install Roblox LSP correctly.

**Comment by Zamdie** [comment]
Thanks, that fixed it!
