### ISSUE TITLE
Remove "Roblox LSP Updates" pop-up.

### ISSUE THREAD

**Issue by TayIorRobinson** [NightrainsRbx/RobloxLsp#118]
Imagine this: You're working on some code, and as you're typing, your code disappears and the LSP Updates window appears.

This isn't great. plz fix. (make it a toast or smth, not a entire window that interrupts your work!)

**Comment by NightrainsRbx** [comment]
I know it may interrupt you, however, it shouldn't interrupt you while you code since it opens when you open VSCode, so it's not a big deal. Also, VSCode Release Notes and many extensions open an update window like Roblox LSP.

**Comment by TayIorRobinson** [comment]
@NightrainsRbx Not always. I had it interrupt my work. (idk what the logic is like for performing update checks in visual studio code is, but it most do checks while you're using it)

**Comment by NightrainsRbx** [comment]
Well, to be specific it opens when the extension initializes, that is, when you open a .lua file, and it opens before the language server starts so it shouldn't have too much delay.

I don't understand why it would open while you are coding.
