### ISSUE TITLE
Automatic import / require statements for modules

### ISSUE THREAD

**Issue by Corecii** [NightrainsRbx/RobloxLsp#122]
A lot of editors support automatically importing matching modules when you use an undefined variable matching the name of a module. I feel like this would be an excellent addition.

I'd be personally happy with whatever the minimum viable first version of this is.
* Automatically finding any matching file is of course awesome, but even automatically filling out imports from a set list is a great start.
* I'd personally only be able to make use of this if it could require by relative path.
* I know lua-language-server has [plugins](https://github.com/sumneko/lua-language-server/wiki/Plugin) -- maybe Roblox LSP could support a Lua plugin that finds and generates requires for undefined variables? Seems like a great way to make it customizable and get a minimum viable version out that isn't very limited.

**Comment by Corecii** [comment]
I'd be interested in investigating implementing this myself, but I'm not sure where to start. Last time I tried to modify and build lua-language-server I couldn't get it to build. Any tips to get started?

**Comment by NightrainsRbx** [comment]
Implementing this as a plugin is possible, but is very hacky since they are meant to add custom syntax, although if you have any idea of how this feature would work I would like to know since I myself don't understand very well how it would work.

> I'd be interested in investigating implementing this myself, but I'm not sure where to start. Last time I tried to modify and build lua-language-server I couldn't get it to build. Any tips to get started?

This repository bundles the language server so you don't need to build it. Just clone this repository and run `npm install` in the client folder, then you can test it by placing it on `%USERPROFILE%\.vscode\extensions` or using https://github.com/sumneko/vscode-lua/blob/master/.vscode/launch.json and running "Launch Client".

**Comment by Corecii** [comment]
> Implementing this as a plugin is possible, but is very hacky since they are meant to add custom syntax, although if you have any idea of how this feature would work I would like to know since I myself don't understand very well how it would work.

When I say "as a plugin" I mean supporting a new plugin function so the end user can define their own automatic import suggestions.

If this were to work like a lot of editors with automatic importing, it would be a "quick fix" suggestion. If a plugin function for generating imports was supported, something like the following could be called if a user chooses "quick fix -> generate import"

```lua
function OnGenerateImport(uri, text, undefinedVariableName)
    -- Assume hasSiblingWithName is implemented elsewhere in this file
    if hasSiblingWithName(uri, undefinedVariableName) then
        return string.format("local %s = require(script.Parent[%q])", undefinedVariableName, undefinedVariableName)
    end
end
```

I don't think this is necessarily the best way to go about this! It's just a suggestion because it might be less work (and more flexible) to get an mvp out if finding and generating require paths is deferred to the user.

---

Good to know that I don't need to build it to try out new things! I may take a look sometime soon and see if I can add auto-import suggestions at some point. Thanks for the tip!
