### ISSUE TITLE
Add types to defined globals

### ISSUE THREAD

**Issue by cmumme** [NightrainsRbx/RobloxLsp#130]
Is there any way to add types to defined globals with RobloxLSP? I'm trying to make a framework that has a build system & automatically inserts a variable that every file will be using at the top of the script, but I can't find a way to properly type this variable. I've tried using overwriting/extending the ENV type, but it doesn't seem like you can do that.

**Comment by NightrainsRbx** [comment]
You can edit env.luau, that should work, keep in mind the file will be overwritten every time the extension updates.

**Comment by cmumme** [comment]
Unfortunately that wouldn't really work for me, as I'd like to distribute it. Thanks for the help though!
