### ISSUE TITLE
Error: spawn UNKNOWN

### ISSUE THREAD

**Issue by OwODeveloper** [NightrainsRbx/RobloxLsp#131]
Starting client failed
Error: spawn UNKNOWN
	at ChildProcess.spawn (internal/child_process.js:403:11)
	at Object.spawn (child_process.js:570:9)
	at c:\Users\User\.vscode\extensions\nightrains.robloxlsp-1.5.5\client\node_modules\vscode-languageclient\lib\node\main.js:407:46

**Comment by OwODeveloper** [comment]
New Year's miracle!

**Comment by NightrainsRbx** [comment]
make sure you have the latest version of VSCode

**Comment by OwODeveloper** [comment]
> make sure you have the latest version of VSCode

last version,
