### ISSUE TITLE
Disable Intellisense for comments

### ISSUE THREAD

**Issue by voshwarthen** [NightrainsRbx/RobloxLsp#15]
Both single-line & block comments give intellisense suggestion. Is there anyway of disabling this?
```lua
-- game:Get

--[[
game:Get
--]]
```

**Comment by NightrainsRbx** [comment]
This does not happen in Roblox LSP, make sure it is not due to another extension like Roblox Auto Fills (which you should disable while using Roblox LSP), or TabNine.
