### ISSUE TITLE
Roblox LSP hide reduce code for blocks on big script

### ISSUE THREAD

**Issue by Aztup** [NightrainsRbx/RobloxLsp#16]
So for some reason on my script i can not reduce `do, if, while`, etc.
It doesn't happens with normal visual studio code.

**Comment by NightrainsRbx** [comment]
I can't replicate the problem, can you be more specific?

It is unlikely to be due to Roblox LSP, since the extension does not modify how VSCode shrinks the blocks.

**Comment by Aztup** [comment]
I tried to find a code with a lots of line and i copied it multiple times and i was able to reproduce the issue with all my plugins turned off for the current workspace. You need to close the file and open it again for the issue to appears

https://pastebin.com/raw/NLRWzrzR

**Comment by NightrainsRbx** [comment]
I found the Issue, but it stills happens when Roblox LSP Is disabled.

**Comment by Aztup** [comment]
Oh.It never happened for me when it's disabled.

**Comment by Aztup** [comment]
Edit: You're right you have to uninstall it.

**Comment by NightrainsRbx** [comment]
> Edit: You're right you have to uninstall it.

I don't understand, disabling it will do the same as uninstalling it, since VSCode never runs it.

**Comment by Aztup** [comment]
Do you want me to give you a video ?

**Comment by Aztup** [comment]
And i'm really sure it has to do it never ever happened for me before.

**Comment by NightrainsRbx** [comment]
> Do you want me to give you a video ?

No problem.

**Comment by Aztup** [comment]
It'll take a few minutes for me to upload the video since i have bad upload sry

**Comment by Aztup** [comment]
Here it is https://streamable.com/ojtnmj

**Comment by Aztup** [comment]
I also saw that when you disable it if you close the file and open it again it's fixed which makes more sense cause that was weird and that part is prob a vs code issue but the other part where when it's turned on it does not works doesn't makes any sense here is the code that reproduce this issue https://pastebin.com/ABm9d6Z5

**Comment by NightrainsRbx** [comment]
I tested the code, and I followed the same steps, except the part of uninstalling the extension, there I just restarted VSCode again.

I found that the problem has to do with Roblox LSP, if you don't use the symbol ``;`` at the end of each statement, everything works fine.

**Comment by Aztup** [comment]
Oh alright i always use `;` cause of eslint lmao.
When you think you could fix it ?

**Comment by NightrainsRbx** [comment]
It probably can't be fixed, but I'll look into it tomorrow.

**Comment by Aztup** [comment]
Oh alright

**Comment by amazman** [comment]
has it been fixed yet, i ran into this

**Comment by Aztup** [comment]
@NightrainsRbx is it gonna be fixed ?

**Comment by NightrainsRbx** [comment]
> @NightrainsRbx is it gonna be fixed ?

Probably after the refactoring.

**Comment by Aztup** [comment]
Hey uh the issue still doesn't seem to be fixed @NightrainsRbx ?
