### ISSUE TITLE
incorrect PARSER_TYPE_AFTER_PACK syntax warning

### ISSUE THREAD

**Issue by noname156** [NightrainsRbx/RobloxLsp#163]
![Screenshot_4](https://user-images.githubusercontent.com/53796817/166126885-b026a0f0-ee6d-4935-af20-6311fccf1779.png)

**Comment by cyrus01337** [comment]
Also receiving this error with the following type:
```lua
export type Function<P, R> = (P) -> R
```

And using it in the following way when implementing a tuple as a generic:
```lua
function Utils.map<C, T>(container: C, callback: Types.Function<(any, any, C), T>): Array<T>
    ...
```

Unsure if bug or a personal mistake, hoping for some type of fix either way.
