### ISSUE TITLE
Lint warning for count-down-loop is incorrect

### ISSUE THREAD

**Issue by incetents** [NightrainsRbx/RobloxLsp#166]
I'm trying to make a simple for loop that iterates: -1, 0, 1. But LSP gives me this warning

![Code_3FmwzwFUfB](https://user-images.githubusercontent.com/22376381/168870577-890227a4-b6a0-4515-b6e0-b262f6d22961.png)

**Comment by NightrainsRbx** [comment]
This lint was removed already in 30470b5df1a092e9ef5fae67aa483b64f0455fa3

**Comment by incetents** [comment]
cool
