### ISSUE TITLE
Force-define files for intellisense/autocomplete

### ISSUE THREAD

**Issue by ovarflode** [NightrainsRbx/RobloxLsp#167]
###### don't judge me for using global tables thx
Unsure how to word the title
This is also a very niche use case
I have a Utils module that I access as `local Utils = shared.Utils`
![image](https://user-images.githubusercontent.com/61893206/169182391-cd827639-00e5-4575-9b16-aa58f10f8ca9.png)

I do this because its a PITA to write: (also `WaitForChild` is gross and slow)
![image](https://user-images.githubusercontent.com/61893206/169185255-41bc725b-73df-4b66-b68d-3abc9885d806.png)

However, it's bothersome to use it this way because autocomplete doesn't work with `shared` / `_G`
I keep on finding myself having to refer back to the Utils module itself

Maybe something like this would work?:
![image](https://user-images.githubusercontent.com/61893206/169183160-f5ce63bc-21e1-4088-b7e3-4c28f898e857.png)
![image](https://user-images.githubusercontent.com/61893206/169185513-6fcf609c-26d6-44fa-b155-e474eb605987.png)

...and it will make the variable behave as if it was defined like this:
![image](https://user-images.githubusercontent.com/61893206/169184935-b93e1140-2d58-493d-8f96-fe5a3456711e.png)

Thanks

**Comment by NightrainsRbx** [comment]
This already exists.
```lua
---@module src.Packages.Setup.Utils
local Utils = shared.Utils
```
Follow the same format.
