### ISSUE TITLE
(better?) Support for adding custom type definitions globally.

### ISSUE THREAD

**Issue by nodomw** [NightrainsRbx/RobloxLsp#168]
I've created a bunch of type definitions for a project I'm working on in hopes of having my custom ones work with IntelliSense. Initially, I tried dragging and dropping the file into `server/def/3rd` inside of the extension folder but that didn't seem to work. Then I tried snooping around the code but I wasn't able to find anything. 

If I am missing some kind of something, please let me know. But if not then I feel like making this easier / adding it would be a great idea.

**Comment by NightrainsRbx** [comment]
You can use `robloxLsp.workspace.library` setting, add the path of a .lua file containing your types to that setting. Exported types will be global across your workspace.

**Comment by nodomw** [comment]
Alright, thank you
