### ISSUE TITLE
New Luau Type Checking

### ISSUE THREAD

**Issue by MrTaco9001** [NightrainsRbx/RobloxLsp#18]
These features are relatively new, so missing support is to be expected. This issue is just to bring it to your attention.

New Luau Type Checking features outlined here: https://devforum.roblox.com/t/luau-type-checking-beta/435382

**Comment by NightrainsRbx** [comment]
Roblox LSP already support current Luau Syntax.

**Comment by MrTaco9001** [comment]
Actually this syntax is not even fully implemented yet in Roblox itself.

Things like shortened math operations (+=, -=, /=, *=) and type safety (local x: number = y)

These are all new features.

**Comment by NightrainsRbx** [comment]
You should read the latest Luau Recap: https://devforum.roblox.com/t/luau-recap-august-2020/719026

Also, in this page created by Roblox shows how Luau works: https://roblox.github.io/luau/ and the Syntax is not outdated.

**Comment by NightrainsRbx** [comment]
Luau is actually usable and the syntax is definitive.

**Comment by MrTaco9001** [comment]
That dev forum post refuses to load for me, but thank you for the link to the documentation. If your plug-in already supports the syntax outlined in the documentation then maybe my VSCode is not configured properly.
