### ISSUE TITLE
Incorrect ends when using types on numeric for loop

### ISSUE THREAD

**Issue by SirMallard** [NightrainsRbx/RobloxLsp#190]
Using types on the index for a numeric for loop will confuse the editor with end autocomplete and collapsed area.

```lua
1   for index: number = 1, 10 do
2   	print(index)
3   end
```

When collapsing `line 1` and any code after `line 1` will be collapsed all under the same header.

For example, the following code:

```lua
1   function issue_function()
2       for index: number = 1, 10 do
3           print(index)
4       end
5   
6       print("after the line")
7   end
8   
9   function any_function(argument: string)
10      return string.upper(argument)
10  end
11  
12  local lower: string = any_function("All this code will be collapsed!")
13  print(lower)
14  
15  return false
```

collapses into:

```lua
1   function issue_function()
16  return false
```
having stopped at the return line for the module script but including the funtion wrapped around the for loop.

Turning `index: number` into just `index` fixes the issue so it is entirely down to the types on the index.

**Comment by NightrainsRbx** [comment]
The syntax for adding annotations to numeric for index is not supported, it's a valid syntax but it's redundant since index can only be a number.
