### ISSUE TITLE
Logo Suggestion

### ISSUE THREAD

**Issue by Almost89** [NightrainsRbx/RobloxLsp#198]
Had an idea for a new logo. Feel free to use it or bin it. Any credit would be great too but absolutely not required.

If you need it in any other format send a reply.

![RobloxLSP](https://user-images.githubusercontent.com/78914413/206919931-237be37b-6966-44ef-aa8c-06886a607c3e.svg)

**Comment by NightrainsRbx** [comment]
Hey, thanks for the suggestion, I think it's a good logo but the P in LSP doesn't need to be bigger that the other letters, actually the other letters are more important since they mean "Language Server".

Thanks anyways!
