### ISSUE TITLE
Syntax highlighting is not very good

### ISSUE THREAD

**Issue by Dekkonot** [NightrainsRbx/RobloxLsp#20]
The syntax highlighting used for the vscode extension is not very good. It highlights `local` as `constant.language` and does not provide special highlighting for Roblox built-in functions. It also highlights `_` as a constant.

**Comment by NightrainsRbx** [comment]
Can you give an example of syntax highlighting for Roblox built-in functions?

**Comment by Dekkonot** [comment]
![image](https://user-images.githubusercontent.com/4625546/95495293-11795800-0954-11eb-8a7d-617ab2eaae43.png)

This is the code snippet that made me notice the issue.

The issues are:
- `typeof` isn't scoped as a built-in function
- `local` is scoped as `constant.language`
- `Instance` is scoped as `support.class`
- the `_` in `_bindable` and `_listeners` is scoped as `constant.numeric.integer.lua`

Quite a few of the built-in functions aren't highlighted properly. As a brief example:
![image](https://user-images.githubusercontent.com/4625546/95495540-70d76800-0954-11eb-990a-bc65a21a8d74.png)
