### ISSUE TITLE
AutoComplete Not working?

### ISSUE THREAD

**Issue by chief1121** [NightrainsRbx/RobloxLsp#23]
I've recently installed the plugin (version v0.11.5), and It was working at first up until I've accidentally installed a Lua plugin from "keyring". After that, the autocomplete stopped working and I've tried reinstalling, restarting my pc, reloading my editor and nothing seems to be working. Please help as soon as possible. And I've also tried looking in settings.

**Comment by NightrainsRbx** [comment]
Have you tried disabling the other Lua plugin you installed?

**Comment by chief1121** [comment]
Yes, sorry for the late response. I've uninstalled all plugins except roblox lsp plugin of course, and still autocomplete broken. It would be great if you had a discord or something so it's easier to track notifications.

**Comment by NightrainsRbx** [comment]
If the rest of plugins are disabled or uninstalled then the problem has to do with Roblox LSP, but most likely it is a bad configuration, make sure everything is set to default.

**Comment by chief1121** [comment]
I've reset all settings, still doesn't work for some reason.

**Comment by NightrainsRbx** [comment]
Test it with another project, also, delete your .vscode folder in your workspace (thats where are your workspace settings).

**Comment by chief1121** [comment]
Hmmmmm, still not working. 

![Aaa](https://user-images.githubusercontent.com/73212373/99201170-01c90c80-2767-11eb-818a-45968b59635f.PNG)

**Comment by chief1121** [comment]
Also, I've tried reverting to other versions before it broke, but no luck. I'm currently on v0.12.1

**Comment by NightrainsRbx** [comment]
How is not working exactly?

**Comment by chief1121** [comment]
For example, I type in game:GetService("Players"). The auto complete doesn't pop up like it's popping up in Roblox studio(the picture provided)
![2020-11-15](https://user-images.githubusercontent.com/73212373/99202144-6b4b1a00-276b-11eb-8da0-9a60b796d180.png)

**Comment by NightrainsRbx** [comment]
Can you show me a gif or a video?

**Comment by chief1121** [comment]
VS:
![Gif](https://user-images.githubusercontent.com/73212373/99205007-9423dd00-2774-11eb-883a-c6546668608c.gif)

**Comment by NightrainsRbx** [comment]
I sent a friend request in Discord, let's talk there.

**Comment by chief1121** [comment]
What's your discord? I have like 60 pending requests.

**Comment by NightrainsRbx** [comment]
Nightrains#8846

**Comment by chief1121** [comment]
You haven't sent one to me, my discord is Term#4134. I've sent you one though.
