### ISSUE TITLE
Roblox's new SharedTable is an undefined global.

### ISSUE THREAD

**Issue by rokoblox** [NightrainsRbx/RobloxLsp#237]
Roblox added a new global [SharedTable](https://create.roblox.com/docs/reference/engine/datatypes/SharedTable) but it wasn't added as a global to roblox LSP yet.

![image](https://github.com/NightrainsRbx/RobloxLsp/assets/40763333/86d6c03c-00f2-4afb-9678-5a24094a7ccc)

**Comment by NerfOrangeman** [comment]
Please Merge This Request 🙏

**Comment by NerfOrangeman** [comment]
please dont forget the new Vector methods
![image](https://github.com/NightrainsRbx/RobloxLsp/assets/104319853/c90f49c3-a86a-4527-bfee-f5d4b27dc7a9)

**Comment by rokoblox** [comment]
This is unrelated to this issue.

**Comment by NightrainsRbx** [comment]
Fixed
