### ISSUE TITLE
Add Support for the Floor Division Operator (//)

### ISSUE THREAD

**Issue by phoriah** [NightrainsRbx/RobloxLsp#247]
![image](https://github.com/NightrainsRbx/RobloxLsp/assets/95628489/7c2e3895-b314-4125-9d5a-edf5b83c21ad)
```lua
print(  (10//8) == math.floor (10/8) ) --> true in Roblox Studio
```
Sources:
https://luau-lang.org/syntax#floor-division-
https://devforum.roblox.com/t/luau-recap-october-2023/2685332#floor-division-1

**Comment by iamEvanYT** [comment]
Bump.

**Comment by ActualMasterOogway** [comment]
bump @NightrainsRbx
