### ISSUE TITLE
How exactly can I get the Roblox LSP plugin to work

### ISSUE THREAD

**Issue by Agentotten** [NightrainsRbx/RobloxLsp#26]
Please help!

![Udklip](https://user-images.githubusercontent.com/61620440/99727482-51d20700-2ab8-11eb-940f-ef4002e82bfb.PNG)
![Udklip](https://user-images.githubusercontent.com/61620440/99727538-6d3d1200-2ab8-11eb-8743-c49010ad8249.PNG)

**Comment by NightrainsRbx** [comment]
What happens when you open http://127.0.0.1:27843/last in your browser, It is not loading or is it a blank page?

**Comment by Agentotten** [comment]
Hey there! Sorry for the late reply, but I could not connect to the site. Do I have to do something to get the extension running?

**Comment by NightrainsRbx** [comment]
You have to open a .lua file to initialize the extension, then go to the link I sent you, if it's blank then it working, if it's not loading then it's not.

**Comment by Agentotten** [comment]
I'm in the .lua file the extension showed a pop up, but it still errors.

**Comment by NightrainsRbx** [comment]
Can you talk to me on Discord? Nightrains#8846

**Comment by Agentotten** [comment]
I can talk in about 2 hours

**Comment by Agentotten** [comment]
I can talk now
