### ISSUE TITLE
Module

### ISSUE THREAD

**Issue by CJJarviis** [NightrainsRbx/RobloxLsp#29]
When I write a script it keeps saying that its a module script and I need to make a module, is there a way to fix that?

**Comment by CJJarviis** [comment]
It says: Module code do not return exactly one value.

**Comment by NightrainsRbx** [comment]
You should have checked the settings before posting an Issue.

If you are using VSCode, go to Settings and find `Lua > Diagnostics: Disable`, then Add "missing-module-return"
![image](https://user-images.githubusercontent.com/69439321/100282875-6a1fa700-2f3a-11eb-8096-96060a01bcd7.png)
