### ISSUE TITLE
RobloxLSP appears to ignore `Lua › Diagnostics: Globals` settings in VSCode

### ISSUE THREAD

**Issue by GlowingUmbreon** [NightrainsRbx/RobloxLsp#32]
I'm creating a script that uses a global that is not normally in roblox, When I add the global to the Settings page I expected it to stop warning me but it still warns me (I believe that it used to stop warning but does not anymore).

I've tried putting the global in both workspace and user settings but they both appear to get ignored.

**Comment by NightrainsRbx** [comment]
I have tested it and it works correctly, maybe you are doing something wrong.

This is how it should look when defining a global:
![image](https://user-images.githubusercontent.com/69439321/102549310-e3b63b00-4089-11eb-865d-f35384c5c545.png)
In .vscode/settings.json:
![image](https://user-images.githubusercontent.com/69439321/102549358-f4ff4780-4089-11eb-8b52-88af454c083c.png)

**Comment by GlowingUmbreon** [comment]
> This is how it should look when defining a global
Yep mine looks like that both in in settings and .vscode/settings.json

**Comment by GlowingUmbreon** [comment]
![image](https://user-images.githubusercontent.com/37640997/102612364-7d342a00-4128-11eb-82d9-75fade9fc4a0.png)
![image](https://user-images.githubusercontent.com/37640997/102612383-86bd9200-4128-11eb-9f28-41d9ade2aff5.png)

**Comment by NightrainsRbx** [comment]
Try using the quick fix, also, try to reset your User and Workspace setting for Lua.diagnostics.globals.

**Comment by GlowingUmbreon** [comment]
> Try using the quick fix, also, try to reset your User and Workspace setting for Lua.diagnostics.globals.

Quick fix just adds another explorer to the settings.
And deleting the settings and then trying to re-add the settings later does not appear to do anything.

**Comment by NightrainsRbx** [comment]
Are other settings working?, like `Lua.diagnostics.disable` which disables the warning itself.

**Comment by GlowingUmbreon** [comment]
Okay just checked, it does not look like other settings are working either.

**Comment by NightrainsRbx** [comment]
Try moving your entire project to another folder, so VSCode detects it like a different workspace.

**Comment by GlowingUmbreon** [comment]
> Try moving your entire project to another folder, so VSCode detects it like a different workspace.

Already tried that, exact same thing.

**Comment by NightrainsRbx** [comment]
Are you using VSCodium?

**Comment by GlowingUmbreon** [comment]
> VSCodium

no
