### ISSUE TITLE
Automatic Parentheses Addition When Auto-Filling a Function or Method

### ISSUE THREAD

**Issue by The-Big-Bird** [NightrainsRbx/RobloxLsp#36]
It would be really handy if Roblox LSP had the option available to automatically place parenthesis after function references.

An example of this would be selecting `print` from a suggestion drop-down and instead of auto-filling just `print` it would auto-fill `print()` and place your cursor in between the parentheses to define arguments.

( Roblox does this in their own built-in editor reference here: https://gyazo.com/57fa00675ce6f9df80a926570d07a5ec )

**Comment by NightrainsRbx** [comment]
You already can just set `Lua.completion.callSnippet` to "Parenthesis" in your settings.
