### ISSUE TITLE
Undefined member behaviour inconsistent

### ISSUE THREAD

**Issue by chess123mate** [NightrainsRbx/RobloxLsp#4]
Referencing the `undefined member` warning in the devforum.roblox.com post:
> When writing the same name twice or more across all the scripts, it will automatically ignored.

There are two problem cases (that I believe are reasonably common):
1. The name of the instance you are referring to has changed (and you referred to it more than once) or you made a typo and copy/pasted that typo into another script. In this case, no warning will result, despite it being an issue that needs fixing.
2. The name is correct, but the project hasn't imported an ignore list. If the name is only used once, a warning will occur.

Suggestions:
- If the user doesn't have a datamodel.json file, either don't trigger this warning for anything, or trigger this warning for everything and include a mention about this "datamodel.json" file in the warning text (ex, "`MyInstance` is not a defined member of `ServerScriptService` in datamodel.json")
- If the user *does* have a datamodel.json file, trigger this warning no matter how many times an instance name shows up across all scripts

**Comment by NightrainsRbx** [comment]
The way it is implemented right now it's a problem, and needs to be changed.

Although most people will not have a .datamodel.json as it is very impractical to use and has to be constantly updated, it will be useful when it can be updated automatically by a Roblox Studio plugin that communicates with the Language Server.

So your suggestions are not the best way to fix this problem.

**Comment by chess123mate** [comment]
I don't understand your conclusion.

The only beneficial thing this warning can do for you is to tell you when you've misspelled something or forgotten to update the name of something. However, if you change the name of something in the place and forget to update it in the scripts, this warning won't trigger if 2+ scripts reference the original name. Doesn't this defeat the main benefit?

I think the best version of this feature (that could be implemented now as far as I know):
- If you use datamodel.json, it could warn you if you try to access any unknown instance
- If you use datamodel.json *and* rojo, any script that rojo would create would be considered "known", even if it wasn't listed in the datamodel.json file
- If you just have a rojo file, it could warn you if you try to require an unknown script (only for areas that rojo is updating)
- If you have neither, it would be silent

If it worked like that, I wouldn't have needed to disable this feature for my projects (as I don't have datamodel.json set up), as it would be rare for it to give a false positive.

All this said, I imagine that it's a ton of effort to implement for minimal benefit, so I understand if you choose to disable the feature. (I wouldn't mind it being disabled, since if I want to get someone set up to use your plugin, disabling this warning would just be another step I'd need to communicate.)

**Comment by NightrainsRbx** [comment]
Hi, just to be clear, I'm not going to disable the undefined member warning, just ignore names that were used twice or more.

And it's because as you said, if you use the name once, you will still get a warning, but if you use the name more times but misspelled, you will not.
