### ISSUE TITLE
module import dims as if unused when it is used for a type import

### ISSUE THREAD

**Issue by matthargett** [NightrainsRbx/RobloxLsp#46]
```lua
local PromiseTypeModule = require(rootWorkspace.luaUtils.Promise)
type Promise<T> = PromiseTypeModule.Promise<T>
```

<img width="687" alt="image" src="https://user-images.githubusercontent.com/1550766/115452989-f8d7dd80-a1d3-11eb-99ff-a5fd8187037a.png">

**Comment by mastapegs** [comment]
Another example of a variable used for a type import, dimmed as if it's unused

![image](https://user-images.githubusercontent.com/13839150/127358644-e1ebf694-a03c-43ff-ad8e-0af42802e494.png)
