### ISSUE TITLE
plans on porting this to the "third party" section of the original language server?

### ISSUE THREAD

**Issue by zainthemaynnn** [NightrainsRbx/RobloxLsp#54]
hey, not sure who here is aware of this already, but the maintainer of the lua language server plans on (or who knows, already has; haven't seen the vscode extension) adding native support for third party APIs in that server. I won't say too much, you can check out a couple of these links.

- [original discussion](https://github.com/sumneko/lua-language-server/issues/409)
- [submissions](https://github.com/sumneko/lua-language-server/discussions/389)
- [frameworks that already exist](https://github.com/sumneko/lua-language-server/tree/master/meta/3rd)

surely some of you here have more experience on this than I. the structure is certainly a major difference (emmylua annotations I think); does anybody believe it would be possible to port the data from here over?

edit: it's not exactly related to this project but the data here may well be the best place to write from. not to mention it could even make this server obsolete if done well enough (although I'm not sure if it can, that's what this issue is about).

**Comment by NightrainsRbx** [comment]
There is not anything to port, Roblox LSP uses the API dump from: https://github.com/CloneTrooper1019/Roblox-Client-Tracker.

From what I see, sumneko wants to implement APIs from other environments with annotations, that would let you have Intellisense for Roblox but it will be much, much more limited, things like requiring modules and rojo support wouldn't be possible, or smart intellisense for things like Events.

What will be better is that the new version of the sumneko's lua language server is more optimized and has many new features, but it is only a matter of time before I decide to port Roblox LSP to that version.

**Comment by zainthemaynnn** [comment]
yeah, I was thinking some of the more advanced features wouldn't be possible. perhaps I will try creating a file anyways for future use, would be strange for such a large platform not be included there. thanks for the info.
