### ISSUE TITLE
Problem with trying to modify extension

### ISSUE THREAD

**Issue by ViniDalvino** [NightrainsRbx/RobloxLsp#65]
I am trying to modify the extension to include new feature for myself however when I click the button to debug the extension it give me this error: 
![image](https://user-images.githubusercontent.com/37189791/126873973-c3ea9410-71ee-43fb-997b-d55f33c8edcd.png)

I tried installing missing depencies with `npm i` and it didn't helped. 

Is there something that I need to do to run the extension?

**Comment by NightrainsRbx** [comment]
Are you running `npm i` inside the client folder?

**Comment by ViniDalvino** [comment]
nah

**Comment by NightrainsRbx** [comment]
You have to run it inside the client folder.
