### ISSUE TITLE
Extension does not work.

### ISSUE THREAD

**Issue by TotallyNotInUse** [NightrainsRbx/RobloxLsp#72]
Hello,

The extension was working fine until one day it stopped autocompleting and it will show wrong problems
![image](https://user-images.githubusercontent.com/56458705/131233043-819a7fd5-5ae8-4247-8726-e7763d517362.png)
I noticed the Lua Language Server is no longer a process in task manager so it might be that.

I disabled every other extension that could be conflicting and only left these:
![image](https://user-images.githubusercontent.com/56458705/131233060-e7150581-82ec-4cb0-8a74-1741961c15a1.png)

The Lua extension by sumneko works fine though.

I also made sure I have enough RAM, reinstalled the extension and restarted VS Code.

Here are other details that may be helpful:

> Version: 1.59.1 (system setup)
> Commit: 3866c3553be8b268c8a7f8c0482c0c0177aa8bfa
> Date: 2021-08-19T11:56:46.957Z
> Electron: 13.1.7
> Chrome: 91.0.4472.124
> Node.js: 14.16.0
> V8: 9.1.269.36-electron.0
> OS: Windows_NT x64 10.0.19042

**Comment by NightrainsRbx** [comment]
Does this happen in another workspace? Could you show me the output?

**Comment by TotallyNotInUse** [comment]
Hello, sorry for the slow answer, the problem fixed itself. Thanks anyways.
