### ISSUE TITLE
Not recognizing '?' for optional parameters on functions when function returns nothing.

### ISSUE THREAD

**Issue by RileyS07** [NightrainsRbx/RobloxLsp#75]
```lua
function example(x: () -> (nil)?)

end
```
The above works.

```lua
function example(x: () -> ()?)

end
```
This gives the following errors:
Missed symbol `)`.
Unexpected symbol `?)`.

**Comment by NightrainsRbx** [comment]
This could be considered a bug and I will fix it, although I would worry about it since `()?` doesn't make any sense.
