### ISSUE TITLE
second argument of `setmetatable` should be required as nil | table

### ISSUE THREAD

**Issue by ok-nick** [NightrainsRbx/RobloxLsp#76]
![image](https://user-images.githubusercontent.com/25470747/131778800-a39f0d54-ebe2-4431-92cb-ee9bb5487b25.png)

**Comment by NightrainsRbx** [comment]
Types are like in Roblox Studio, where it says it requires two arguments:
![image](https://user-images.githubusercontent.com/69439321/131781170-1e2cec7e-ce6f-4f78-91d8-dc256aad06ba.png)

Maybe you got confused?

**Comment by ok-nick** [comment]
The second parameter of `setmetatable` should be optional

**Comment by NightrainsRbx** [comment]
Yeah, you are correct, but not optional, but nil or table.

**Comment by NightrainsRbx** [comment]
To do that I would have to create another kind of type, just a union of nil and table wouldn't work.

**Comment by ok-nick** [comment]
By optional, I meant `nil | table`. I'm assuming you mean that the lsp doesn't default unspecified parameters as `nil`?

**Comment by NightrainsRbx** [comment]
When a parameter is optional (or nil | table), it can be skipped when calling the function.

**Comment by NightrainsRbx** [comment]
The problem is that, when calling setmetatable without the second argument, it throws this error:
![image](https://user-images.githubusercontent.com/69439321/131782760-659812f1-53fd-4aa0-8b36-40a5f638ebc8.png)

**Comment by ok-nick** [comment]
Oh, my bad. I thought I remembered it automatically defaulting to nil... guess I was wrong, I'll close this

**Comment by Baileyeatspizza** [comment]
yeah i keep having to deal with this issue as well
![image](https://user-images.githubusercontent.com/68239467/132992045-54c10a89-e7f8-4d36-9d57-212a4200d276.png)
