### ISSUE TITLE
declaring type alias causes unexpected <exp> error

### ISSUE THREAD

**Issue by murmanox** [NightrainsRbx/RobloxLsp#8]
![image](https://user-images.githubusercontent.com/53511594/90222711-8886ea00-de04-11ea-9e5f-7e79286fa19e.png)

**Comment by NightrainsRbx** [comment]
Roblox LSP doens't support full Luau syntax yet.

To use it, you have to install Selene too.

Read more here: https://devforum.roblox.com/t/roblox-lsp-full-intellisense-for-roblox-and-luau/717745

**Comment by murmanox** [comment]
sorry
