### ISSUE TITLE
Find All References for module function broken in vscode since 1.0.0++

### ISSUE THREAD

**Issue by ldhongen1990** [NightrainsRbx/RobloxLsp#81]
@NightrainsRbx After updating RobloxLSP extension for vscode from 0.15.11 to 1.0.0++, "Find All References" for module function no longer works. Nothing will be shown. If you install an older version 0.15.11, you can check that it will work. Will love to have it working in the latest RobloxLSP version.

Edit: It doesn't work across files as it used to. I can no longer use "Find All References" to get a list of code in other file calling my module function. For example: MathUtil.GetRange() in MathUtil.lua, if you "Find All References" to GetRange() function, you can not longer see that it has been used in A.lua and B.lua, etc etc.

**Comment by NightrainsRbx** [comment]
Thanks for reporting it, I will look into fixing this for the next version.
