### ISSUE TITLE
The instance.new function will always appear in the autofill options if you type n

### ISSUE THREAD

**Issue by basedIdiot** [NightrainsRbx/RobloxLsp#87]
The instance.new function will appear in autofill option where it shouldn't, like when typing out Vector3.n. This happens in all my lua files, but it doesn't happen while typing out comments.
![image](https://user-images.githubusercontent.com/88017350/133026835-eceaaa63-e755-41fe-aa7b-efc9159c4cd2.png)

**Comment by NightrainsRbx** [comment]
That's not from Roblox LSP, it is from https://marketplace.visualstudio.com/items?itemName=Kampfkarren.roblox-lua-autofills.
