### ISSUE TITLE
Typecheck Strict Mode issue with Value Objects

### ISSUE THREAD

**Issue by ldhongen1990** [NightrainsRbx/RobloxLsp#89]
@NightrainsRbx Hello there, any ideas why these are not working?

![image](https://user-images.githubusercontent.com/17633734/133220773-c3becda8-28a7-4684-9790-4b80fda63681.png)

![image](https://user-images.githubusercontent.com/17633734/133220826-839746bc-b151-48d0-9a6e-51f6e9da5fbb.png)

**Comment by NightrainsRbx** [comment]
It is inferring both Changed from BoolValue and Changed from Instance, so it ends up inferring two types. This is a bug.
