### ISSUE TITLE
Extension not working as intended and stuck on "Reloading workspace..."

### ISSUE THREAD

**Issue by nzzp** [NightrainsRbx/RobloxLsp#92]
I just installed it today and it worked fine until I clicked the extension on the status bar of VSCode

![image](https://user-images.githubusercontent.com/61440265/133912715-6444b870-c2c7-426e-9136-1402052b78b6.png)

**Comment by NightrainsRbx** [comment]
It doesn't appear to be reloading the workspace, the notificacion doesn't hide when the reloading is finished but after a few seconds.

Open the VSCode Output, and check the "Lua" output if it appears.

**Comment by nzzp** [comment]
I can't seem to find the "Lua" output in the output windoww
![image](https://user-images.githubusercontent.com/61440265/133912856-26bd9cc4-cab5-4340-bc96-a697cb259e52.png)
+

**Comment by nzzp** [comment]
My bad, I think this is an output from the extension but it doesn't seem to show the "reloading workspace..." output
![image](https://user-images.githubusercontent.com/61440265/133914630-35aee1d7-a4c2-438d-b16c-cc07a70c93a9.png)

**Comment by nzzp** [comment]
Do I need to install anything before using the extension?

**Comment by nzzp** [comment]
Fixed ^^ Roblox LSP only works on `.lua` files not `.luau`
