### ISSUE TITLE
serialize can't pack too depth table

### ISSUE THREAD

**Issue by christopher-buss** [NightrainsRbx/RobloxLsp#98]
When I have studio running the LSP extension, I get this error: I have two place files that I am currently working on, and this only occurs using one of the files, the other does not have this error with LSP.

...nightrains.robloxlsp-1.3.1\server\script\brave\brave.lua:34: serialize can't pack too depth table
stack traceback:
	[C]: in method 'push'
	...nightrains.robloxlsp-1.3.1\server\script\brave\brave.lua:34: in function 'brave.brave.push'
	...\nightrains.robloxlsp-1.3.1\server\script\brave\work.lua:17: in function <...\nightrains.robloxlsp-1.3.1\server\script\brave\work.lua:8>
	[C]: in function 'xpcall'
	...nightrains.robloxlsp-1.3.1\server\script\brave\brave.lua:55: in function 'brave.brave.start'
	...nightrains.robloxlsp-1.3.1\server\script\brave\brave.lua:23: in function 'brave.brave.register'
	[string "package.path  = "c:\\Users\\chris\\.vscode\\e..."]:13: in main chunk
	[C]: in ?

This breaks the intellisense compeltely and does not allow me to use the extension.

I can provide more details where needed but unsure what is relevant and what isn't :)

**Comment by NightrainsRbx** [comment]
This was a bug of the Roblox Studio Plugin, is fixed in the latest update.
